/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package insertion.sort;

import org.junit.jupiter.api.Test;

import java.util.Arrays;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {

  @Test void insertionSort() {
    int[] regularArr = {8, 4, 23, 42, 16, 15};
    assertEquals("[4, 8, 15, 16, 23, 42]", Arrays.toString(Insertion.InsertionSort(regularArr)));
  }

  @Test void mergeSort(){
    int[] regularArr = {8, 4, 23, 42, 16, 15};
    assertEquals("[4, 8, 15, 16, 23, 42]", Arrays.toString(Insertion.mergeSort(regularArr)));
  }

  @Test void quickSort(){
    int[] regularArr = {8, 4, 23, 42, 16, 15};
    assertEquals("[4, 8, 15, 16, 23, 42]", Arrays.toString(Insertion.quickSort(regularArr,0,5)));
  }
}

