/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashmap.repeated.word;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

  public static void main(String[] args) {
    String text = "It was a queer, sultry summer, the summer they electrocuted the Rosenbergs, and I didn’t know what I was doing in New York...";
    System.out.println(RepeatedWord.repeatedWord(text));
  }
}
