/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linked.list;

import linked.list.data.Node;
import linked.list.structure.SinglyLinkedList;

public class Main {
  public static void main(String[] args) throws Exception {
    System.out.println("Hello World");

    System.out.println("\n======================================================");
    System.out.println("\nLinked List Demo \n");

    SinglyLinkedList linkedList = new SinglyLinkedList();
    linkedList.insert("L");
    linkedList.insert("A");
    linkedList.insert("W");
    linkedList.insert("W");
    linkedList.insert("A");
    linkedList.insert("L");
    linkedList.append("ZZZZZZZZZZ");

//    linkedList.insertAfter("N","00");
//    linkedList.insertBefore("L", "55");
    System.out.println(linkedList.kthFromEnd(3));
    System.out.println(linkedList.toString());

    SinglyLinkedList ll = new SinglyLinkedList();
    ll.insert("1");
    ll.insert("2");
    ll.insert("3");
    ll.insert("3");
    ll.insert("2");
    ll.insert("1");

    System.out.println(linkedList);
//    System.out.println(linkedList.isPalindrome());
//    System.out.println(ll.isPalindrome());
    System.out.println("\n======================================================");
    System.out.println(linkedList.includes("J"));
    System.out.println(linkedList.includes("L"));
    System.out.println(linkedList.includes("M"));
    System.out.println(linkedList.kthFromEnd(2));

    System.out.println("\n======================================================");

  }
}
