/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linked.list;

import linked.list.structure.LinkedList;

public class Main {
  public static void main(String[] args) {
    System.out.println("Hello World");

    System.out.println("\n======================================================");
    System.out.println("\nLinked List Demo \n");

    LinkedList linkedList = new LinkedList();
    linkedList.insert("L");
    linkedList.insert("A");
    linkedList.insert("W");
    linkedList.insert("A");
    linkedList.insert("N");
    System.out.println(linkedList.toString());

    System.out.println("\n======================================================");
    System.out.println(linkedList.includes("J"));
    System.out.println(linkedList.includes("L"));
    System.out.println(linkedList.includes("M"));

    System.out.println("\n======================================================");
  }
}
