/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linked.list;

import linked.list.structure.SinglyLinkedList;

public class Main {
  public static void main(String[] args) throws Exception {
    System.out.println("Hello World");

    System.out.println("\n======================================================");
    System.out.println("\nLinked List Demo \n");

    SinglyLinkedList linkedList = new SinglyLinkedList();
    linkedList.insert("L");
    linkedList.insert("A");
    linkedList.insert("W");
    linkedList.insert("A");
    linkedList.insert("N");
    linkedList.insertBefore("N","00");
    linkedList.insertAfter("L", "55");
    System.out.println(linkedList.toString());

    System.out.println("\n======================================================");
    System.out.println(linkedList.includes("J"));
    System.out.println(linkedList.includes("L"));
    System.out.println(linkedList.includes("M"));
    System.out.println(linkedList.kthFromEnd(2));

    System.out.println("\n======================================================");

  }
}
