/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashmap.left.join;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.function.Supplier;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

  public static void main(String[] args) {
    HashMap<String, String> hashmap1 = new HashMap<>();
    HashMap<String, String> hashmap2 = new HashMap<>();

    List<String> result = new ArrayList<>();

    hashmap1.put("fond", "enamored");
    hashmap1.put("wrath", "anger");
    hashmap1.put("diligent", "employed");
    hashmap1.put("outfit", "garb");
    hashmap1.put("guide", "usher");


    hashmap2.put("fond", "averse");
    hashmap2.put("wrath", "delight");
    hashmap2.put("diligent", "idle");
    hashmap2.put("guide", "follow");
    hashmap2.put("flow", "jam");

    System.out.println(LeftJoin.leftJoin(hashmap1 , hashmap2));
//    System.out.println("Should equal"+ resultlt.leftJoinin(hashmap1, hashmap2));

  }
}
