/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stack.and.queue;

import stack.and.queue.structure.PseudoQueue;
import stack.and.queue.structure.Queue;
import stack.and.queue.structure.Stack;

import java.sql.PseudoColumnUsage;

public class Library {
  public static void main(String[] args) throws Exception {

    System.out.println("===========================================================Stack test===========================================================");
    Stack stack = new Stack();
    stack.isEmpty();
    System.out.println(stack.isEmpty());
    stack.push("Hello");
    stack.push("From");
    stack.push("Stack");
    System.out.println(stack.peek());
//    stack.pop();
    System.out.println(stack.peek());
    System.out.println("================================================================================================================================");

    System.out.println("===========================================================Queue test===========================================================");
    Queue queue = new Queue();
    System.out.println(queue.isEmpty());
    queue.enqueue("Hey");
    queue.enqueue("From");
    queue.enqueue("Queue");
    System.out.println(queue.peek());
    queue.dequeue();
    System.out.println(queue.peek());


    System.out.println("===========================================================Pseudo Queue test===========================================================");
    PseudoQueue first= new PseudoQueue();
    System.out.println(first.dequeue());
    first.enqueue("Hey");
    first.enqueue("From");
    first.enqueue("Queue");
    System.out.println(first.getSize());
    first.dequeue();
    System.out.println(first.getSize());
}

}
