/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph;


public class Library {
  public boolean someLibraryMethod() {
    return true;
  }

  public static void main(String[] args) {
    Graph BreadthFirst = new Graph();
    Vertex a = BreadthFirst.addVertex("Pandora");
    Vertex b =  BreadthFirst.addVertex("Arendelle");
    Vertex c = BreadthFirst.addVertex("Metroville");
    Vertex d = BreadthFirst.addVertex("Monstropolis");
    Vertex e = BreadthFirst.addVertex("Narnia");
    Vertex f = BreadthFirst.addVertex("Naboo");

    BreadthFirst.addEdge("Pandora","Arendelle");
    BreadthFirst.addEdge("Arendelle","Metroville");
    BreadthFirst.addEdge("Arendelle","Monstropolis");
    BreadthFirst.addEdge("Metroville","Narnia");
    BreadthFirst.addEdge("Metroville","Naboo");
    BreadthFirst.addEdge("Monstropolis","Naboo");
    BreadthFirst.addEdge("Narnia","Naboo");

    System.out.println("\nBreadth First Start with Vertex" + " 'Pandora'" + ":");
    BreadthFirst.breadthFirst(a);
    System.out.println("\n\n");
  }

}
