/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashmap.left.join;

import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.function.Supplier;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
  public static void main(String[] args) {
    HashMap<String, String> hashmap1 = new HashMap<>();
    HashMap<String, String> hashmap2 = new HashMap<>();

    hashmap1.put("fond", "enamored");
    hashmap1.put("wrath", "anger");
    hashmap1.put("diligent", "employed");
    hashmap1.put("outfit", "garb");
    hashmap1.put("guide", "usher");


    hashmap2.put("fond", "averse");
    hashmap2.put("wrath", "delight");
    hashmap2.put("diligent", "idle");
    hashmap2.put("guide", "follow");
    hashmap2.put("flow", "jam");

    List<String> list = new ArrayList<>();
    list.add("diligent: employed, idle");
    list.add("outfit: garb, Null");
    list.add("wrath: anger, delight");
    list.add("guide: usher, follow");
    list.add("fond: enamored, averse");

    assertEquals(list, LeftJoin.leftJoin(hashmap1, hashmap2));
  }

}
