/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {

  @Test void addVertexTest(){
    Graph graph = new Graph();
    graph.addVertex("Sudoku");
    graph.addVertex("chess");
    graph.addVertex("Pubg");
    assertEquals(graph.getVertex(), graph.getVertex());
  }

  @Test void AddEdgeTest(){
    Graph graph = new Graph();
    graph.addVertex("Sudoku");
    graph.addVertex("chess");
    graph.addVertex("Pubg");

    graph.addEdge("Sudoku", "chess");
    graph.addEdge("Sudoku", "Pubg");
    graph.addEdge("Sudoku", "Sudoku");
    graph.addEdge("chess", "Pubg");
    assertEquals("[Vertex{label='Sudoku', weight=0}, Vertex{label='chess', weight=0}, Vertex{label='Pubg', weight=0}]",graph.getVertex().toString());
  }

  @Test
  public void emptyGraphTest(){
    Graph graph = new Graph();
    assertEquals(0,graph.size());
  }
}
