/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {

  @Test void AddNodeTest(){
    Graph graph = new Graph();
    graph.addNode("Sudoku");
    graph.addNode("chess");
    graph.addNode("Pubg");
    assertEquals(graph.getNodes(), graph.getNodes());
  }

  @Test void AddEdgeTest(){
    Graph graph = new Graph();
    graph.addNode("Sudoku");
    graph.addNode("chess");
    graph.addNode("Pubg");

    graph.addEdge("Sudoku", "chess");
    graph.addEdge("Sudoku", "Pubg");
    graph.addEdge("Sudoku", "Sudoku");
    graph.addEdge("chess", "Pubg");
    assertEquals("[Vertex{label='Sudoku', weight=0}, Vertex{label='chess', weight=0}, Vertex{label='Pubg', weight=0}]",graph.getNodes().toString());
  }

  @Test
  public void emptyGraphTest(){
    Graph graph = new Graph();
    assertEquals(0,graph.size());
  }
}
